In [3]:
import pandas as pd

In [4]:
import numpy as np

In [9]:
np.random.seed(0)
weekly_sales = np.random.randint(20, size=(5,3))

In [10]:
weekly_sales

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [28]:
total_sales = pd.DataFrame(weekly_sales, index = ["mon","tues","wed","thurs","fri"], columns = ["almond butter","peanut butter","cashew butter"])

In [29]:
total_sales

almond butter  peanut butter  cashew butter
mon               12             15              0
tues               3              3              7
wed                9             19             18
thurs              4              6             12
fri                1              6              7

In [16]:
weekly_sales.shape

(5, 3)

In [18]:
total_sales.shape

(5, 3)

In [23]:
price = np.array([10,8,12])


In [24]:
price

array([10,  8, 12])

In [30]:
total_sales

almond butter  peanut butter  cashew butter
mon               12             15              0
tues               3              3              7
wed                9             19             18
thurs              4              6             12
fri                1              6              7

In [33]:
total_sales_price = pd.DataFrame(price , index=["prices"], columns = ["almnond butter", "peanut butter", "cashew butter"])

ValueError: Shape of passed values is (3, 1), indices imply (1, 3)

In [34]:
price.shape

(3,)

In [35]:
new_price = price.reshape(1,3)

In [36]:
new_price

array([[10,  8, 12]])

In [37]:
total_sales_price = pd.DataFrame(new_price , index=["prices"], columns = ["almnond butter", "peanut butter", "cashew butter"])

In [38]:
total_sales_price

almnond butter  peanut butter  cashew butter
prices              10              8             12

In [39]:
new_total_sales = np.dot(total_sales,total_sales_price)

ValueError: shapes (5,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [40]:
total_sales.shape

(5, 3)

In [41]:
total_sales_price.shape

(1, 3)

In [42]:
new_total_sales_price = total_sales_price.T

In [43]:
new_total_sales_price

prices
almnond butter      10
peanut butter        8
cashew butter       12

In [44]:
new_total_sales_price.shape

(3, 1)

In [45]:
total_sales.shape

(5, 3)

In [46]:
new_product_sales = np.dot(total_sales,new_total_sales_price)

In [47]:
new_product_sales

array([[240],
       [138],
       [458],
       [232],
       [142]])

In [48]:
total_sales

almond butter  peanut butter  cashew butter
mon               12             15              0
tues               3              3              7
wed                9             19             18
thurs              4              6             12
fri                1              6              7

In [62]:
total_sales["earnings"] = new_product_sales

In [63]:
total_sales

almond butter  peanut butter  cashew butter  earnings  pricess
mon               12             15              0       240      NaN
tues               3              3              7       138      NaN
wed                9             19             18       458      NaN
thurs              4              6             12       232      NaN
fri                1              6              7       142      NaN

In [64]:
total_sales["pricess"].dropna

<bound method Series.dropna of mon     NaN
tues    NaN
wed     NaN
thurs   NaN
fri     NaN
Name: pricess, dtype: float64>

In [65]:
total_sales

almond butter  peanut butter  cashew butter  earnings  pricess
mon               12             15              0       240      NaN
tues               3              3              7       138      NaN
wed                9             19             18       458      NaN
thurs              4              6             12       232      NaN
fri                1              6              7       142      NaN

In [67]:
total_sales.drop("pricess", axis = 1)

almond butter  peanut butter  cashew butter  earnings
mon               12             15              0       240
tues               3              3              7       138
wed                9             19             18       458
thurs              4              6             12       232
fri                1              6              7       142

In this way we created entire dataframe through array and we have calculated earnings of the days by using dot product and is represented as above.  